* 어절: 문장에서 발음의 단위
  * ex) '우리는 오늘 동해로 간다' --> 4개 어절
* 음절: 최소의 발음 단위
  * ex) '우', '리', '는', '오', '늘', '동', '해', '로', '간', '다'

In [15]:
from konlpy.tag import Komoran

# n_gram 유사도
# 1. 명사 토큰화, 2. 토큰 n-gram화, 3. 비율세기

# 어절 단위 n-gram
def word_ngram(bow, num_gram):
    text = tuple(bow)
    print("n_gram_bow= ", text)
    end_idx = len(text)//num_gram
    print(end_idx)
    ngrams = [text[x:x + num_gram] for x in range(0, len(text)-num_gram+1)]
    #ngrams = [text[x:x + num_gram] for x in range(0, end_idx)]
    return tuple(ngrams)


# 음절 n-gram 분석
def phoneme_ngram(bow, num_gram):
    sentence = ' '.join(bow)
    text = tuple(sentence)
    slen = len(text)
    ngrams = [text[x:x + num_gram] for x in range(0, slen)]
    return ngrams


# 유사도 계산
def similarity(doc1, doc2):
    cnt = 0
    for token in doc1:
        if token in doc2:
            cnt = cnt + 1

    return cnt/len(doc1)


sentence1 = '1666년 6월에 뉴턴은 선생님의 제안으로 트리니티에 입학하였다'
sentence2 = '1666년 6월에 뉴턴은 선생님의 제안으로 대학교에 입학하였다'
sentence3 = '나는 맛잇는 밥을 뉴턴 선생님과 함께 먹었습니다.'

komoran = Komoran()
bow1 = komoran.nouns(sentence1)
bow2 = komoran.nouns(sentence2)
bow3 = komoran.nouns(sentence3)
print("bow1: ", bow1)
print("bow2: ", bow2)
print("bow3: ", bow3)

doc1 = word_ngram(bow1, 2)
doc2 = word_ngram(bow2, 2)
doc3 = word_ngram(bow3, 2)

print("n_gram out: ", doc1)
print("n_gram out: ", doc2)
print("n_gram out: ", doc3)

r1 = similarity(doc1, doc2)
r2 = similarity(doc3, doc1)
print("유사도: ", r1)
print("유사도: ", r2)




doc1 = word_ngram(bow1, 3)
doc2 = word_ngram(bow2, 3)
doc3 = word_ngram(bow3, 3)

print("n_gram out: ", doc1)
print("n_gram out: ", doc2)
print("n_gram out: ", doc3)

r1 = similarity(doc1, doc2)
r2 = similarity(doc3, doc1)
print("유사도: ", r1)
print("유사도: ", r2)



doc1 = word_ngram(bow1, 4)
doc2 = word_ngram(bow2, 4)
doc3 = word_ngram(bow3, 4)

print("n_gram out: ", doc1)
print("n_gram out: ", doc2)
print("n_gram out: ", doc3)

r1 = similarity(doc1, doc2)
r2 = similarity(doc3, doc1)
print("유사도: ", r1)
print("유사도: ", r2)


bow1:  ['년', '6월', '뉴턴', '선생님', '제안', '트리니티', '입학']
bow2:  ['년', '6월', '뉴턴', '선생님', '제안', '대학교', '입학']
bow3:  ['맛', '밥', '뉴턴', '선생', '님과 함께']
n_gram_bow=  ('년', '6월', '뉴턴', '선생님', '제안', '트리니티', '입학')
3
n_gram_bow=  ('년', '6월', '뉴턴', '선생님', '제안', '대학교', '입학')
3
n_gram_bow=  ('맛', '밥', '뉴턴', '선생', '님과 함께')
2
n_gram out:  (('년', '6월'), ('6월', '뉴턴'), ('뉴턴', '선생님'), ('선생님', '제안'), ('제안', '트리니티'), ('트리니티', '입학'))
n_gram out:  (('년', '6월'), ('6월', '뉴턴'), ('뉴턴', '선생님'), ('선생님', '제안'), ('제안', '대학교'), ('대학교', '입학'))
n_gram out:  (('맛', '밥'), ('밥', '뉴턴'), ('뉴턴', '선생'), ('선생', '님과 함께'))
유사도:  0.6666666666666666
유사도:  0.0
n_gram_bow=  ('년', '6월', '뉴턴', '선생님', '제안', '트리니티', '입학')
2
n_gram_bow=  ('년', '6월', '뉴턴', '선생님', '제안', '대학교', '입학')
2
n_gram_bow=  ('맛', '밥', '뉴턴', '선생', '님과 함께')
1
n_gram out:  (('년', '6월', '뉴턴'), ('6월', '뉴턴', '선생님'), ('뉴턴', '선생님', '제안'), ('선생님', '제안', '트리니티'), ('제안', '트리니티', '입학'))
n_gram out:  (('년', '6월', '뉴턴'), ('6월', '뉴턴', '선생님'), ('뉴턴', '선생님', '제안'), ('선생님', '제안', '대학교'), 

[질문] 그림 5-2예시랑 코드 결과랑 마지막 성분이 다름, 코드는 마지막 성분이 unigram으로 하나 더 추가로 나옴
--> len(text)-1 --> len(text) - num_n + 1

In [21]:
from konlpy.tag import Komoran

# n_gram 유사도
# 1. 명사 토큰화, 2. 토큰 n-gram화, 3. 비율세기

class n_gram():

    # 어절 단위 n-gram
    def word_ngram(bow, num_gram):
        text = tuple(bow)
        #print("n_gram_bow= ", text)
        end_idx = len(text)//num_gram
        #print(end_idx)
        ngrams = [text[x:x + num_gram] for x in range(0, len(text)-num_gram+1)]
        return tuple(ngrams)


    # 음절 n-gram 분석
    def phoneme_ngram(bow, num_gram):
        sentence = ' '.join(bow)
        text = tuple(sentence)
        slen = len(text)
        ngrams = [text[x:x + num_gram] for x in range(0, slen)]
        return ngrams


    # 유사도 계산
    def similarity(doc1, doc2):
        cnt = 0
        for token in doc1:
            if token in doc2:
                cnt = cnt + 1

        return cnt/len(doc1)
    
    
if __name__ == '__main__':

    while True:
        sentence1 = input("3개 이상의 단어로 구성된 문장1을(를) 입력하세요\n예:사람은 표유류에 속하는 동물이다\n문장1 :")
        sentence2 = input("3개 이상의 단어로 구성된 문장2을(를) 입력하세요\n예:사람은 설치류에 속하는 동물이다\n문장2 :")
        if len(sentence1) > 0 and len(sentence2) > 0:
            break
    #sentence1 = input("문장1(기준)을 입력하세요: ")
    #sentence2 = input("문장2(비교)를 입력하세요: ")
  
    komoran = Komoran()
    bow1 = komoran.nouns(sentence1)
    bow2 = komoran.nouns(sentence2)
    print("bow1: ", bow1)
    print("bow2: ", bow2)

    doc1 = n_gram.word_ngram(bow1, 2)
    doc2 = n_gram.word_ngram(bow2, 2)

    print("n_gram out: ", doc1)
    print("n_gram out: ", doc2)

    r1 = n_gram.similarity(doc1, doc2)
    print("유사도: ", r1)


bow1:  ['집안일', '로봇', '집안일', '동영상', '분만', '터득']
bow2:  ['집안일', '로봇', '스승', '동영상']
n_gram out:  (('집안일', '로봇'), ('로봇', '집안일'), ('집안일', '동영상'), ('동영상', '분만'), ('분만', '터득'))
n_gram out:  (('집안일', '로봇'), ('로봇', '스승'), ('스승', '동영상'))
유사도:  0.2


In [20]:
# sentence1 = "사람은 포유류에 속하는 동물이다"
# sentence2 = "사람은 설치류에 속하는 동물이다"
# sentence3 = "지우개는 필통에 넣는 물건이다"
# sentence4 = "지우개는 필통에 넣는 학용품이다"
# sentence5 = '2023년 6월 20일 늦은 저녁부터 오늘 새벽까지 비가 많이왔고, 기온도 3도 이상 떨어졌다'
# sentence6 = '2023년 6월 20일 늦은 저녁부터 오늘 새벽까지 비가 많이 왔다'
# sentence7 = '집안일 돕는 로봇은, 집안일 동영상을 보고 25분만에 터득했다'
# sentence8 = "집안일 돕는 로봇, 스승은 동영상"






n_gram out:  (('사람', '포유류'), ('포유류', '속'), ('속', '동물'))
n_gram out:  (('사람', '설치류'), ('설치류', '속'), ('속', '동물'))
n_gram out:  (('지우개', '필통'), ('필통', '물건'))
n_gram out:  (('지우개', '필통'), ('필통', '학용품'), ('학용품', '이다'))
n_gram out:  (('년', '6월 20일'), ('6월 20일', '저녁'), ('저녁', '오늘'), ('오늘', '새벽'), ('새벽', '비'), ('비', '기온'), ('기온', '이상'))
n_gram out:  (('년', '6월 20일'), ('6월 20일', '저녁'), ('저녁', '오늘'), ('오늘', '새벽'), ('새벽', '비'))
n_gram out:  (('집안일', '로봇'), ('로봇', '집안일'), ('집안일', '동영상'), ('동영상', '분만'), ('분만', '터득'))
n_gram out:  (('집안일', '로봇'), ('로봇', '스승'), ('스승', '동영상'))
유사도:  0.3333333333333333
유사도:  0.5
유사도:  0.7142857142857143
유사도:  0.2


In [25]:
#예제-5-2-코사인 유사도 계산
from konlpy.tag import Komoran
import numpy as np
from numpy import dot
from numpy.linalg import norm


# 코사인 유사도 계산-1
def cos_sim(vec1, vec2):
    return dot(vec1, vec2) / (norm(vec1) * norm(vec2))
 

# TDM 만들기-2
# 전체 단어 셋트와 비교문장 단어 세트 비교해서 count
def make_term_doc_mat(sentence_bow, word_dics):
    freq_mat = {}
    for word in word_dics:
        freq_mat[word] = 0
    for word in word_dics:
        if word in sentence_bow:
            freq_mat[word] += 1
    return freq_mat


# 단어 벡터 만들기-3, 
# make_term_doc_mat 여기서 만든 dict의 value값 삽입
def make_vector(tdm):
    vec = []
    for key in tdm:
        vec.append(tdm[key])
    return vec
 
# 문장 정의
sentence1 = '6월에 뉴턴은 선생님의 제안으로 트리니티에 입학하였다'
sentence2 = '6월에 뉴턴은 선생님의 제안으로 대학교에 입학하였다'
sentence3 = '나는 맛잇는 밥을 뉴턴 선생님과 함께 먹었습니다.'
 
# 헝태소분석기를 이용해 단어 묶음 리스트 생성-4
komoran = Komoran()
bow1 = komoran.nouns(sentence1)
bow2 = komoran.nouns(sentence2)
bow3 = komoran.nouns(sentence3)
 
# 단어 묶음 리스트를 하나로 합침-5
bow = bow1 + bow2 + bow3
print("bow: ", bow)
 
# 단어 묶음에서 중복제거해 단어 사전 구축-6
word_dics = []
for token in bow:
    if token not in word_dics:
        word_dics.append(token)
print("word_dics: ", word_dics)
 
# 문장 별 단어 문서 행렬 계산-7
freq_list1 = make_term_doc_mat(bow1, word_dics)
freq_list2 = make_term_doc_mat(bow2, word_dics)
freq_list3 = make_term_doc_mat(bow3, word_dics)
print(freq_list1)
print(freq_list2)
print(freq_list3)
 
# 문장 백터 생성-8
doc1 = np.array(make_vector(freq_list1))
doc2 = np.array(make_vector(freq_list2))
doc3 = np.array(make_vector(freq_list3))
print(doc1)
print(doc2)
print(doc3)
 
# 코사인 유사도 계산-9
r1 = cos_sim(doc1, doc2)
r2 = cos_sim(doc3, doc1)
print(r1)
print(r2)

bow:  ['6월', '뉴턴', '선생님', '제안', '트리니티', '입학', '6월', '뉴턴', '선생님', '제안', '대학교', '입학', '맛', '밥', '뉴턴', '선생', '님과 함께']
word_dics:  ['6월', '뉴턴', '선생님', '제안', '트리니티', '입학', '대학교', '맛', '밥', '선생', '님과 함께']
{'6월': 1, '뉴턴': 1, '선생님': 1, '제안': 1, '트리니티': 1, '입학': 1, '대학교': 0, '맛': 0, '밥': 0, '선생': 0, '님과 함께': 0}
{'6월': 1, '뉴턴': 1, '선생님': 1, '제안': 1, '트리니티': 0, '입학': 1, '대학교': 1, '맛': 0, '밥': 0, '선생': 0, '님과 함께': 0}
{'6월': 0, '뉴턴': 1, '선생님': 0, '제안': 0, '트리니티': 0, '입학': 0, '대학교': 0, '맛': 1, '밥': 1, '선생': 1, '님과 함께': 1}
[1 1 1 1 1 1 0 0 0 0 0]
[1 1 1 1 0 1 1 0 0 0 0]
[0 1 0 0 0 0 0 1 1 1 1]
0.8333333333333335
0.18257418583505536


In [26]:
#예제-5-2-코사인 유사도 계산
from konlpy.tag import Komoran
import numpy as np
from numpy import dot
from numpy.linalg import norm


# 코사인 유사도 계산-1
def cos_sim(vec1, vec2):
    return dot(vec1, vec2) / (norm(vec1) * norm(vec2))
 

# TDM 만들기-2
# 전체 단어 셋트와 비교문장 단어 세트 비교해서 count
def make_term_doc_mat(sentence_bow, word_dics):
    freq_mat = {}
    for word in word_dics:
        freq_mat[word] = 0
    for word in word_dics:
        if word in sentence_bow:
            freq_mat[word] += 1
    return freq_mat


# 단어 벡터 만들기-3, 
# make_term_doc_mat 여기서 만든 dict의 value값 삽입
def make_vector(tdm):
    vec = []
    for key in tdm:
        vec.append(tdm[key])
    return vec
 
# 문장 정의
sentence1 = '6월에 뉴턴은 선생님의 제안으로 트리니티에 입학하였다'
sentence2 = '6월에 뉴턴은 선생님의 제안으로 선생님의 대학교에 입학하였다'
sentence3 = '나는 맛잇는 밥을 뉴턴 선생님과 함께 먹었습니다.'
 
# 헝태소분석기를 이용해 단어 묶음 리스트 생성-4
komoran = Komoran()
bow1 = komoran.nouns(sentence1)
bow2 = komoran.nouns(sentence2)
bow3 = komoran.nouns(sentence3)
 
# 단어 묶음 리스트를 하나로 합침-5
bow = bow1 + bow2 + bow3
print("bow: ", bow)
 
# 단어 묶음에서 중복제거해 단어 사전 구축-6
word_dics = []
for token in bow:
    if token not in word_dics:
        word_dics.append(token)
print("word_dics: ", word_dics)
 
# 문장 별 단어 문서 행렬 계산-7
freq_list1 = make_term_doc_mat(bow1, word_dics)
freq_list2 = make_term_doc_mat(bow2, word_dics)
freq_list3 = make_term_doc_mat(bow3, word_dics)
print(freq_list1)
print(freq_list2)
print(freq_list3)
 
# 문장 백터 생성-8
doc1 = np.array(make_vector(freq_list1))
doc2 = np.array(make_vector(freq_list2))
doc3 = np.array(make_vector(freq_list3))
print(doc1)
print(doc2)
print(doc3)
 
# 코사인 유사도 계산-9
r1 = cos_sim(doc1, doc2)
r2 = cos_sim(doc3, doc1)
print(r1)
print(r2)

bow:  ['6월', '뉴턴', '선생님', '제안', '트리니티', '입학', '6월', '뉴턴', '선생님', '제안', '선생님', '대학교', '입학', '맛', '밥', '뉴턴', '선생', '님과 함께']
word_dics:  ['6월', '뉴턴', '선생님', '제안', '트리니티', '입학', '대학교', '맛', '밥', '선생', '님과 함께']
{'6월': 1, '뉴턴': 1, '선생님': 1, '제안': 1, '트리니티': 1, '입학': 1, '대학교': 0, '맛': 0, '밥': 0, '선생': 0, '님과 함께': 0}
{'6월': 1, '뉴턴': 1, '선생님': 1, '제안': 1, '트리니티': 0, '입학': 1, '대학교': 1, '맛': 0, '밥': 0, '선생': 0, '님과 함께': 0}
{'6월': 0, '뉴턴': 1, '선생님': 0, '제안': 0, '트리니티': 0, '입학': 0, '대학교': 0, '맛': 1, '밥': 1, '선생': 1, '님과 함께': 1}
[1 1 1 1 1 1 0 0 0 0 0]
[1 1 1 1 0 1 1 0 0 0 0]
[0 1 0 0 0 0 0 1 1 1 1]
0.8333333333333335
0.18257418583505536


In [40]:
import pandas as pd

import numpy as np

# 데이터를 시각화 할 때 필요한 라이브러리들

import seaborn as sns

import matplotlib.pyplot as plt

 

df = sns.load_dataset("penguins")

#일부 데이터만 보기

df.head()

# 데이터 길이

len (df) # 344

 

df.shape # (344, 7)

 

# 요약정보 보기

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   species            344 non-null    object 
 1   island             344 non-null    object 
 2   bill_length_mm     342 non-null    float64
 3   bill_depth_mm      342 non-null    float64
 4   flipper_length_mm  342 non-null    float64
 5   body_mass_g        342 non-null    float64
 6   sex                333 non-null    object 
dtypes: float64(4), object(3)
memory usage: 18.9+ KB


In [43]:
#예제-5-2-코사인 유사도 계산
from konlpy.tag import Komoran
import numpy as np
from numpy import dot
from numpy.linalg import norm


# 코사인 유사도 계산-1
def cos_sim(vec1, vec2):
    return dot(vec1, vec2) / (norm(vec1) * norm(vec2))
 
# TDM 만들기-2
# 전체 단어 셋트와 비교문장 단어 세트 비교해서 count
def make_term_doc_mat(sentence_bow, word_dics):
    freq_mat = {}
    for word in word_dics:
        freq_mat[word] = 0
    for word in word_dics:
        if word in sentence_bow:
            freq_mat[word] += 1
    return freq_mat


# 단어 벡터 만들기-3, 
# make_term_doc_mat 여기서 만든 dict의 value값 삽입
def make_vector(tdm):
    vec = []
    for key in tdm:
        vec.append(tdm[key])
    return vec
 

if __name__ == '__main__':

    while True:
        sentence1 = input("3개 이상의 단어로 구성된 문장1을(를) 입력하세요\n예:사람은 표유류에 속하는 동물이다\n문장1 :")
        sentence2 = input("3개 이상의 단어로 구성된 문장2을(를) 입력하세요\n예:사람은 설치류에 속하는 동물이다\n문장2 :")
        sentence3 = input("3개 이상의 단어로 구성된 문장3을(를) 입력하세요\n예:사람은 설치류에 속하는 동물이다\n문장3 :")
        if len(sentence1) > 0 and len(sentence2) and len(sentence3) > 0:
            break

    # 문장 정의
    #sentence1 = '6월에 뉴턴은 선생님의 제안으로 트리니티에 입학하였다'
    #sentence2 = '6월에 뉴턴은 선생님의 제안으로 선생님의 대학교에 입학하였다'
    #sentence3 = '나는 맛잇는 밥을 뉴턴 선생님과 함께 먹었습니다.'

    # 헝태소분석기를 이용해 단어 묶음 리스트 생성-4
    komoran = Komoran()
    bow1 = komoran.nouns(sentence1)
    bow2 = komoran.nouns(sentence2)
    bow3 = komoran.nouns(sentence3)
    
    # 단어 묶음 리스트를 하나로 합침-5
    bow = bow1 + bow2 + bow3
    print("모든 문장 명사 추출: ", bow)
    
    # 단어 묶음에서 중복제거해 단어 사전 구축-6
    word_dics = []
    for token in bow:
        if token not in word_dics:
            word_dics.append(token)
    print("모든 문장 명사 중복 제거: ", word_dics)
    
    # 문장 별 단어 문서 행렬 계산-7
    freq_list1 = make_term_doc_mat(bow1, word_dics)
    freq_list2 = make_term_doc_mat(bow2, word_dics)
    freq_list3 = make_term_doc_mat(bow3, word_dics)
    print("문장1 명사 카운트 dict: ", freq_list1)
    print("문장2 명사 카운트 dict: ", freq_list2)
    print("문장3 명사 카운트 dict: ", freq_list3)
    
    # 문장 백터 생성-8
    doc1 = np.array(make_vector(freq_list1))
    doc2 = np.array(make_vector(freq_list2))
    doc3 = np.array(make_vector(freq_list3))
    print("문장1 명사 벡터: ", doc1)
    print("문장2 명사 벡터: ", doc2)
    print("문장3 명사 벡터: ", doc3)
    
    # 코사인 유사도 계산-9
    r1 = cos_sim(doc1, doc2)
    r2 = cos_sim(doc3, doc1)
    print("문장1, 문장2의 코사인유사도: ", r1)
    print("문장3, 문장1의 코사인유사도: ", r2)

모든 문장 명사 추출:  ['6월', '뉴턴', '선생님', '제안', '트리니티', '입학', '6월', '뉴턴', '선생님', '제안', '선생님', '대학교', '입학', '맛', '밥', '뉴턴', '선생', '님과 함께']
모든 문장 명사 중복 제거:  ['6월', '뉴턴', '선생님', '제안', '트리니티', '입학', '대학교', '맛', '밥', '선생', '님과 함께']
문장1 명사 카운트 dict:  {'6월': 1, '뉴턴': 1, '선생님': 1, '제안': 1, '트리니티': 1, '입학': 1, '대학교': 0, '맛': 0, '밥': 0, '선생': 0, '님과 함께': 0}
문장2 명사 카운트 dict:  {'6월': 1, '뉴턴': 1, '선생님': 1, '제안': 1, '트리니티': 0, '입학': 1, '대학교': 1, '맛': 0, '밥': 0, '선생': 0, '님과 함께': 0}
문장3 명사 카운트 dict:  {'6월': 0, '뉴턴': 1, '선생님': 0, '제안': 0, '트리니티': 0, '입학': 0, '대학교': 0, '맛': 1, '밥': 1, '선생': 1, '님과 함께': 1}
문장1 명사 벡터:  [1 1 1 1 1 1 0 0 0 0 0]
문장2 명사 벡터:  [1 1 1 1 0 1 1 0 0 0 0]
문장3 명사 벡터:  [0 1 0 0 0 0 0 1 1 1 1]
문장1, 문장2의 코사인유사도:  0.8333333333333335
문장3, 문장1의 코사인유사도:  0.18257418583505536
