In [2]:
import konlpy
konlpy.__version__

'0.6.0'

In [23]:
from konlpy.tag import Komoran
import numpy as np

def komoran_nouns(komoran, text):
    print("=="*80)
    print("<입력 문장: ", text, ">")
    #print("\n")
    print("<실행결과>")
    # 형태소와 품사 태그 추출
    nouns = komoran.nouns(text)
    print("명사 추출: ", nouns)

    # 단어 사전 구축 및 단어별 인덱스 부여
    dics = {}
    for word in nouns:
        if word not in dics.keys():
            dics[word] = len(dics)
    print("단어사전: ", dics)

    # 원핫 인코딩
    nb_classes = len(dics)
    targets = list(dics.values())
    one_hot_targets = np.eye(nb_classes)[targets]
    #one_hot_targets = np.eye(nb_classes)
    #one_hot_targets = np.eye(nb_classes)[[0,2,1]]
    #one_hot_targets = np.eye(nb_classes)[0,2,1]
    print("원핫벡터: ")

    return print(one_hot_targets)


komoran = Komoran()
text1 = "오늘 점심에 비가 올까요 안올까요"
text2 = "오늘 점심에 비와 천둥번개가 점심에 올까요 안올까요"

komoran_nouns(komoran, text1)
komoran_nouns(komoran, text2)


<입력 문장:  오늘 점심에 비가 올까요 안올까요 >
<실행결과>
명사 추출:  ['오늘', '점심', '비']
단어사전:  {'오늘': 0, '점심': 1, '비': 2}
원핫벡터: 
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
<입력 문장:  오늘 점심에 비와 천둥번개가 점심에 올까요 안올까요 >
<실행결과>
명사 추출:  ['오늘', '점심', '비와', '천둥', '번개', '점심']
단어사전:  {'오늘': 0, '점심': 1, '비와': 2, '천둥': 3, '번개': 4}
원핫벡터: 
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


#### word2vec model 실습

In [24]:
!pip install gensim konlpy

                                              0.0/24.0 MB ? eta -:--:--
     --                                       1.5/24.0 MB 31.4 MB/s eta 0:00:01
     --------                                 5.1/24.0 MB 54.4 MB/s eta 0:00:01
     -----------------                       10.5/24.0 MB 81.8 MB/s eta 0:00:01
     -------------------------              15.8/24.0 MB 108.8 MB/s eta 0:00:01
     ---------------------------------      21.2/24.0 MB 131.2 MB/s eta 0:00:01
     -------------------------------------  24.0/24.0 MB 108.8 MB/s eta 0:00:01
     -------------------------------------  24.0/24.0 MB 108.8 MB/s eta 0:00:01
     --------------------------------------- 24.0/24.0 MB 54.7 MB/s eta 0:00:00
                                              0.0/56.8 kB ? eta -:--:--
     ---------------------------------------- 56.8/56.8 kB ? eta 0:00:00


In [30]:
from gensim.models import Word2Vec
from konlpy.tag import Komoran
import time


# 네이버 영화 리뷰 데이터 읽어옴
def read_review_data(filename):
    with open(filename, 'r', encoding="utf8") as f:
        data = [line.split('\t') for line in f.read().splitlines()]
        data = data[1:] # header 제거
    return data


# 측정 시작
start = time.time()

# 리뷰 파일 읽어오기
print('1) 말뭉치 데이터 읽기 시작')
review_data = read_review_data('C:/workspace/VScode_project/prj2/chatbot/book_ex/ch4/ratings.txt')
print(len(review_data)) # 리뷰 데이터 전체 개수
print('1) 말뭉치 데이터 읽기 완료: ', time.time() - start)
#review_data

# 문장단위로 명사만 추출해 학습 입력 데이터로 만듬
print('2) 형태소에서 명사만 추출 시작')
komoran = Komoran()
docs = [komoran.nouns(sentence[1]) for sentence in review_data]
print('2) 형태소에서 명사만 추출 완료: ', time.time() - start)



1) 말뭉치 데이터 읽기 시작
200000
1) 말뭉치 데이터 읽기 완료:  0.329120397567749
2) 형태소에서 명사만 추출 시작
2) 형태소에서 명사만 추출 완료:  101.51767992973328


In [34]:
docs

[['때'],
 ['디자인',
  '학생',
  '외국',
  '디자이너',
  '전통',
  '발전',
  '문화',
  '산업',
  '사실',
  '우리나라',
  '시절',
  '끝',
  '열정',
  '노라',
  '노',
  '전통',
  '사람',
  '꿈',
  '수',
  '것',
  '감사'],
 ['폴리스', '스토리', '시리즈', '뉴', '최고'],
 ['연기', '것', '라고', '생각', '몰입', '영', '화지'],
 ['안개', '밤하늘', '초승달', '영화'],
 ['사랑', '사람', '처음', '끝', '수', '영화'],
 ['완전', '감동', '감동'],
 ['개들의 전쟁', '빠'],
 ['굿'],
 ['바보', '병', '인', '듯'],
 ['나이',
  '영화',
  '감동',
  '하지',
  '훗날',
  '다시',
  '보면',
  '대사',
  '하나하나',
  '감정',
  '을',
  '완벽',
  '이해',
  '것'],
 [],
 ['고질라', '무'],
 ['영화', '오페라', '작품', '극단', '평', '수', '듯'],
 ['반전', '제'],
 ['평점', '긴장감', '스릴', '감', '최고', '전장', '공포'],
 ['고시', '에이', '터', '소재', '뿐', '관련'],
 ['최고'],
 ['밀회', '화이팅', '!!'],
 ['생각', '상당', '수작', '일본', '영화', '10년', '내', '최고', '마음', '임팩트', '일품'],
 ['오랜만', '범죄', '스릴러'],
 ['때',
  '사랑해',
  '마디',
  '말',
  '밤',
  '잠',
  '때',
  '징',
  '교복',
  '남은',
  '션',
  '자이',
  '볼펜',
  '자국',
  '마음',
  '형태',
  '거'],
 ['마지막', '씨', '수'],
 ['강압', '용서', '세뇌', '적', '용서', '비판'],
 ['중세', '시대', '명작', '굿',

질문
1. word2vec/sg=1의 학습과정
  - 윈도우가4인데 2번째 리스트["디자인", "학생", "외국" ... "것", "감사"]가 들어왔을때 윈도우에 값이 없으면 어떻게 처리
  - size --> vector_size=200 --> rgb가 3차원이라면 이설정은 200차원이라고 생각하면 되는지 --> hidden size = 200

In [50]:
start = time.time()

# word2vec 모델 학습
print('3) word2vec 모델 학습 시작')
#model = Word2Vec(sentences=docs, size=200, window=4, min_count=2, sg=1)
model = Word2Vec(sentences=docs, vector_size=200, window=4, min_count=2, sg=1)
print('3) word2vec 모델 학습 완료: ', time.time() - start)

# 모델 저장
print('4) 학습된 모델 저장 시작')
model.save('../INC/nvmc.model')
print('4) 학습된 모델 저장 완료: ', time.time() - start)

# 학습된 말뭉치 개수, 코퍼스 내 전체 단어 개수
print("corpus_count : ", model.corpus_count)
print("corpus_total_words : ", model.corpus_total_words)


3) word2vec 모델 학습 시작


Exception in thread Thread-228:
Traceback (most recent call last):
  File "c:\Python38\lib\threading.py", line 932, in _bootstrap_inner
Exception in thread Thread-230:
Traceback (most recent call last):
  File "c:\Python38\lib\threading.py", line 932, in _bootstrap_inner
Exception in thread Thread-229:
Traceback (most recent call last):
  File "c:\Python38\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "c:\Python38\lib\threading.py", line 870, in run
    self.run()
  File "c:\Python38\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "c:\Python38\lib\site-packages\gensim\models\word2vec.py", line 1166, in _worker_loop
    self.run()
  File "c:\Python38\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "c:\Python38\lib\site-packages\gensim\models\word2vec.py", line 1166, in _worker_loop
    tally, raw_tally = self._do_train_job(data_iterable, alpha, thread_private_mem)
  File "c:\Python

In [1]:
from gensim.models import Word2Vec

# 모델 로딩
model = Word2Vec.load('../INC/nvmc.model')
print("corpus_total_words : ", model.corpus_total_words)

# '사랑'이란 단어로 생성한 단어 임베딩 벡터
print('사랑 : ', model.wv['사랑'])
print('안성기 : ', model.wv['안성기'])
print('안성기 : ', len(model.wv['안성기']))

# 단어 유사도 계산 --> 코사인유사도 -1 ~ 1
print("일요일 = 월요일\t", model.wv.similarity(w1='일요일', w2='월요일'))
print("안성기 = 배우\t", model.wv.similarity(w1='안성기', w2='배우'))
print("대기업 = 삼성\t", model.wv.similarity(w1='대기업', w2='삼성'))
print("일요일 != 삼성\t", model.wv.similarity(w1='일요일', w2='삼성'))
print("히어로 != 삼성\t", model.wv.similarity(w1='히어로', w2='삼성'))

# 가장 유사한 단어 추출
print(model.wv.most_similar("안성기", topn=5))
print(model.wv.most_similar("시리즈", topn=5))

corpus_total_words :  1076896
사랑 :  [-0.12441562 -0.3108967   0.37153587  0.04936414 -0.24691921 -0.10323611
  0.08638293  0.11379326 -0.29101694  0.4911757  -0.23907314 -0.03547018
  0.4615035  -0.44226623 -0.19473636  0.19259782  0.01307585 -0.31161478
 -0.21792227 -0.19937606  0.25766742  0.29444626  0.16360968  0.30629456
 -0.21854752 -0.26202723  0.0671104  -0.26346958 -0.16620965 -0.03032559
  0.03689308  0.11473958  0.5535217  -0.02473382 -0.00197884  0.05359099
  0.02282135 -0.28798205 -0.3029894   0.00897885  0.05747567  0.06269748
  0.0485414  -0.25221843  0.7719562   0.32691252 -0.08043284 -0.18667324
  0.39050862  0.03148877 -0.01545839 -0.08963436 -0.1872682   0.28831038
 -0.15469907 -0.1738586  -0.33475688 -0.30211502 -0.15466869  0.16490638
  0.00745399 -0.250198   -0.15207677  0.14882746  0.05716898 -0.03587583
 -0.30653346  0.1112955  -0.14091782  0.7142276   0.18096517 -0.00933327
  0.59034115  0.20408067  0.33187386 -0.18981437  0.40743452 -0.32242852
 -0.32551703 -0